name: Deploy Firebase Cloud Functions

on:
  push:
    branches:
      - main  # Se a sua branch principal no GitHub se chamar 'master', mude aqui para 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependencias do Backend
        run: |
          cd functions
          npm install

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticar e Fazer Deploy na Nuvem
        run: |
          echo "$GCP_SA_KEY" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          firebase deploy --only functions --project jornal-dr
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
